'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, LoaderCircle } from 'lucide-react';
import { supabase } from '../../../lib/supabase/client';

const ranks = ['Champion', 'Grand Champion 1', 'Grand Champion 2', 'Grand Champion 3', 'SSL', 'CRL-Level', 'Custom'];
const regions = ['NA East', 'NA Central', 'NA West', 'EU', 'Other / Custom'];

export default function NewTeamPage() {
  const [user, setUser] = useState(null); const [schools, setSchools] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  const [form, setForm] = useState({ school_id: '', name: '', rank: 'Grand Champion 2', region: 'NA East', school_email: '', supporting_url: '' });
  useEffect(() => { async function load() { const { data: { user: activeUser } } = await supabase.auth.getUser(); if (!activeUser) { window.location.assign('/auth'); return; } setUser(activeUser); const { data, error: schoolError } = await supabase.from('schools').select('id,name').order('name'); if (schoolError) setError(schoolError.message); else setSchools(data || []); setLoading(false); } load(); }, []);
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  async function submit(e) { e.preventDefault(); setError(''); setSaving(true); const { data: team, error: teamError } = await supabase.from('teams').insert({ ...form, captain_id: user.id }).select('id').single(); if (teamError) { setError(teamError.message); setSaving(false); return; } const { error: memberError } = await supabase.from('team_members').insert({ team_id: team.id, user_id: user.id, role: 'captain' }); if (memberError) { setError(memberError.message); setSaving(false); return; } setDone(true); setSaving(false); }
  if (loading) return <main className="form-page"><LoaderCircle className="spin" size={22}/></main>;
  if (done) return <main className="form-page"><section className="form-card success-card"><CheckCircle2 size={35}/><p className="eyebrow">VERIFICATION SUBMITTED</p><h1>Your team is in review.</h1><p>We’ll email you when your collegiate status is approved or rejected. Until then, your roster can be set up but cannot use the marketplace.</p><Link href="/" className="primary">Back to Scrimnet <ArrowRight size={16}/></Link></section></main>;
  return <main className="form-page"><section className="form-card"><Link href="/" className="back"><ArrowLeft size={15}/> Back to marketplace</Link><p className="eyebrow">TEAM VERIFICATION</p><h1>Create your team.</h1><p className="form-subtitle">Every team is manually verified before it can post or request scrims.</p>{error && <div className="auth-error">{error}</div>}<form onSubmit={submit}><label>College or university<select required value={form.school_id} onChange={e=>update('school_id',e.target.value)}><option value="">Select your school</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Team name<input required value={form.name} onChange={e=>update('name',e.target.value)} placeholder="e.g. BGSU" /><small>Displayed publicly as “{form.name || 'Your team'} Rocket League.”</small></label><div className="two-fields"><label>Rocket League level<select value={form.rank} onChange={e=>update('rank',e.target.value)}>{ranks.map(rank=><option key={rank}>{rank}</option>)}</select></label><label>Region<select value={form.region} onChange={e=>update('region',e.target.value)}>{regions.map(region=><option key={region}>{region}</option>)}</select></label></div><label>School email<input required type="email" value={form.school_email} onChange={e=>update('school_email',e.target.value)} placeholder="you@school.edu" /><small>Used only for manual verification.</small></label><label>Official club/team link <span>Optional</span><input type="url" value={form.supporting_url} onChange={e=>update('supporting_url',e.target.value)} placeholder="https://…" /></label><button className="primary form-submit" disabled={saving}>{saving && <LoaderCircle className="spin" size={17}/>} Submit for verification <ArrowRight size={17}/></button></form></section></main>;
}
