-- Scrimnet initial schema. Run this in Supabase SQL Editor before using auth/team flows.
create type public.team_role as enum ('captain', 'manager', 'member');
create type public.verification_status as enum ('pending', 'approved', 'rejected', 'revoked');
create type public.scrim_status as enum ('posted', 'confirmed', 'played', 'completed', 'cancelled', 'archived');
create type public.request_status as enum ('pending', 'accepted', 'declined', 'withdrawn');
create type public.report_status as enum ('open', 'reviewing', 'resolved', 'dismissed');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null unique check(char_length(username) between 3 and 30), notification_preference text not null default '24_hours' check(notification_preference in ('immediately','12_hours','24_hours','72_hours','never')), is_admin boolean not null default false, suspended_at timestamptz, created_at timestamptz not null default now());
create table public.schools (id uuid primary key default gen_random_uuid(), name text not null unique, email_domain text, verified boolean not null default false, created_at timestamptz not null default now());
create table public.teams (id uuid primary key default gen_random_uuid(), name text not null check(char_length(name) between 2 and 60), school_id uuid not null references public.schools(id), game text not null default 'Rocket League' check(game = 'Rocket League'), rank text not null, region text not null, verification_status public.verification_status not null default 'pending', school_email text, supporting_url text, captain_id uuid not null references public.profiles(id), suspended_at timestamptz, created_at timestamptz not null default now(), unique(school_id,name,game));
create table public.team_members (id uuid primary key default gen_random_uuid(), team_id uuid not null references public.teams(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.team_role not null default 'member', joined_at timestamptz not null default now(), unique(team_id,user_id));
create table public.scrims (id uuid primary key default gen_random_uuid(), posting_team_id uuid not null references public.teams(id), opponent_team_id uuid references public.teams(id), game text not null default 'Rocket League' check(game = 'Rocket League'), min_rank text not null, max_rank text not null, region text not null, scheduled_at timestamptz not null, duration_minutes integer not null check(duration_minutes between 15 and 360), format text not null, notes text check(char_length(notes) <= 500), status public.scrim_status not null default 'posted', replacement_needed boolean not null default false, created_at timestamptz not null default now());
create table public.scrim_requests (id uuid primary key default gen_random_uuid(), scrim_id uuid not null references public.scrims(id) on delete cascade, requesting_team_id uuid not null references public.teams(id), message text check(char_length(message) <= 500), status public.request_status not null default 'pending', created_at timestamptz not null default now(), unique(scrim_id,requesting_team_id));
create table public.scrim_checkins (id uuid primary key default gen_random_uuid(), scrim_id uuid not null references public.scrims(id) on delete cascade, team_id uuid not null references public.teams(id), checked_in_by uuid not null references public.profiles(id), checked_in_at timestamptz not null default now(), unique(scrim_id,team_id));
create table public.scrim_reschedules (id uuid primary key default gen_random_uuid(), scrim_id uuid not null references public.scrims(id) on delete cascade, requested_by_team_id uuid not null references public.teams(id), old_time timestamptz not null, proposed_time timestamptz not null, message text check(char_length(message) <= 500), status public.request_status not null default 'pending', created_at timestamptz not null default now());
create table public.scrim_cancellations (id uuid primary key default gen_random_uuid(), scrim_id uuid not null references public.scrims(id) on delete cascade, canceled_by_team_id uuid not null references public.teams(id), late_cancel boolean not null, created_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), scrim_id uuid not null references public.scrims(id) on delete cascade, user_id uuid not null references public.profiles(id), body text not null check(char_length(body) between 1 and 1000), deleted_at timestamptz, created_at timestamptz not null default now());
create table public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public.profiles(id), reported_user_id uuid references public.profiles(id), reported_team_id uuid references public.teams(id), message_id uuid references public.messages(id), reason text not null check(char_length(reason) between 5 and 1000), status public.report_status not null default 'open', created_at timestamptz not null default now(), check(reported_user_id is not null or reported_team_id is not null or message_id is not null));

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,username) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce((select is_admin from public.profiles where id=auth.uid()),false); $$;
create or replace function public.is_team_member(target_team uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.team_members where team_id=target_team and user_id=auth.uid()); $$;
create or replace function public.can_manage_team(target_team uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.team_members where team_id=target_team and user_id=auth.uid() and role in ('captain','manager')); $$;

alter table public.profiles enable row level security; alter table public.schools enable row level security; alter table public.teams enable row level security; alter table public.team_members enable row level security; alter table public.scrims enable row level security; alter table public.scrim_requests enable row level security; alter table public.scrim_checkins enable row level security; alter table public.scrim_reschedules enable row level security; alter table public.scrim_cancellations enable row level security; alter table public.messages enable row level security; alter table public.reports enable row level security;
create policy "profiles readable" on public.profiles for select to authenticated using(true); create policy "users update profile" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "schools readable" on public.schools for select to authenticated using(true); create policy "admins manage schools" on public.schools for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "approved teams readable" on public.teams for select to authenticated using(verification_status='approved' or public.is_team_member(id) or public.is_admin()); create policy "users create teams" on public.teams for insert to authenticated with check(captain_id=auth.uid()); create policy "managers update teams" on public.teams for update to authenticated using(public.can_manage_team(id) or public.is_admin());
create policy "members readable" on public.team_members for select to authenticated using(public.is_team_member(team_id) or public.is_admin());
create policy "managers manage members" on public.team_members for all to authenticated using(public.can_manage_team(team_id) or public.is_admin()) with check(public.can_manage_team(team_id) or public.is_admin() or (user_id=auth.uid() and role='captain' and exists(select 1 from public.teams where id=team_id and captain_id=auth.uid())));
create policy "scrims readable" on public.scrims for select to authenticated using(status='posted' or public.is_team_member(posting_team_id) or public.is_team_member(opponent_team_id) or public.is_admin()); create policy "managers post scrims" on public.scrims for insert to authenticated with check(public.can_manage_team(posting_team_id)); create policy "managers update scrims" on public.scrims for update to authenticated using(public.can_manage_team(posting_team_id) or public.can_manage_team(opponent_team_id) or public.is_admin());
create policy "participants read requests" on public.scrim_requests for select to authenticated using(public.is_team_member(requesting_team_id) or exists(select 1 from public.scrims s where s.id=scrim_id and public.is_team_member(s.posting_team_id)) or public.is_admin()); create policy "managers request" on public.scrim_requests for insert to authenticated with check(public.can_manage_team(requesting_team_id));
create policy "participants read messages" on public.messages for select to authenticated using(exists(select 1 from public.scrims s where s.id=scrim_id and (public.is_team_member(s.posting_team_id) or public.is_team_member(s.opponent_team_id))) or public.is_admin()); create policy "participants send messages" on public.messages for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from public.scrims s where s.id=scrim_id and (public.is_team_member(s.posting_team_id) or public.is_team_member(s.opponent_team_id))));
create policy "users create reports" on public.reports for insert to authenticated with check(reporter_id=auth.uid()); create policy "admins read reports" on public.reports for select to authenticated using(public.is_admin());
create index scrims_marketplace_idx on public.scrims(status,game,region,scheduled_at) where status='posted'; create index team_members_user_idx on public.team_members(user_id); create index messages_scrim_created_idx on public.messages(scrim_id,created_at);
